// Core type definitions for HeroBrawl

export type FactionId =
  | "vanguard"
  | "horde"
  | "wildwood"
  | "arcane"
  | "radiance"
  | "abyss";

export type ClassId =
  | "guardian"
  | "berserker"
  | "mage"
  | "assassin"
  | "ranger"
  | "cleric";

export type Rarity = 1 | 2 | 3 | 4 | 5; // 1=Common, 5=Legendary

export interface Faction {
  id: FactionId;
  name: string;
  color: string;
  accent: string;
  lore: string;
  strongVs: FactionId[];
}

export interface HeroClass {
  id: ClassId;
  name: string;
  role: string;
  description: string;
  baseStats: HeroStats;
}

export interface HeroStats {
  attack: number;
  health: number;
  armor: number;
  speed: number;
  willpower: number; // control immunity
}

export interface Skill {
  id: string;
  name: string;
  description: string;
  kind: "active" | "passive";
  energyCost?: number;
  cooldown?: number;
  // Effect tuning
  power?: number; // damage multiplier or heal amount
  aoe?: boolean;
  target?: "enemy" | "ally" | "self" | "all-enemies" | "all-allies";
  status?: StatusEffect;
}

export type StatusKind =
  | "burn"
  | "poison"
  | "stun"
  | "shield"
  | "regen"
  | "attack-up"
  | "armor-break";

export interface StatusEffect {
  kind: StatusKind;
  duration: number;
  magnitude: number;
}

export interface HeroTemplate {
  id: string;
  name: string;
  title: string;
  faction: FactionId;
  class: ClassId;
  baseRarity: Rarity;
  emoji: string; // stand-in sprite
  portraitGradient: [string, string];
  signatureColor: string;
  bio: string;
  skills: Skill[];
}

export interface HeroInstance {
  instanceId: string; // unique to this owned hero
  templateId: string;
  level: number;
  stars: Rarity; // can grow past baseRarity via ascension
  xp: number;
  echoStacks: number; // from duplicates
  gearTier: number; // 0-6
  equippedStone?: StoneKind;
}

export type StoneKind = "crit" | "attack" | "speed" | "energy" | "health";

export interface CurrencyState {
  gold: number;
  gems: number;
  spirit: number;
  prophetOrbs: number;
  heroicScrolls: number;
  basicScrolls: number;
  shards: number; // generic ascension
  dust: number; // skill upgrades
}

export interface IdleState {
  startedAt: number; // epoch ms
  tickedAt: number; // last claim time
  ratePerHour: IdleRates;
  capHours: number; // max accrual hours
}

export interface IdleRates {
  gold: number;
  spirit: number;
  shards: number;
}

export interface Lineup {
  // slots 0..4 (front row 0,1,2; back row 3,4)
  slots: (string | null)[]; // instanceIds
}

export interface CampaignProgress {
  chapter: number; // 1..10
  stage: number; // 1..10 per chapter
}

export interface ArenaState {
  rating: number;
  wins: number;
  losses: number;
  lastFight: number;
  ticketsUsed: number;
  ticketDay: string;
}

export interface QuestState {
  day: string; // ISO date
  progress: Record<string, number>;
  claimed: Record<string, boolean>;
  completionClaimed: boolean;
}

export interface GachaState {
  heroicPulls: number; // total
  pityCount: number; // 60 = guaranteed legendary
  sinceEpic: number; // 10 = guaranteed 4★+
}

export interface BrawlPoints {
  value: number; // currency generated by winning battles
}

export interface GameState {
  version: number;
  createdAt: number;
  playerName: string;
  playerLevel: number;
  playerXp: number;
  currency: CurrencyState;
  heroes: HeroInstance[];
  lineup: Lineup;
  idle: IdleState;
  campaign: CampaignProgress;
  arena: ArenaState;
  quests: QuestState;
  gacha: GachaState;
  brawl: BrawlPoints;
  messages: GameMessage[];
  settings: { sound: boolean; confetti: boolean };
}

export interface GameMessage {
  id: string;
  at: number;
  text: string;
  kind: "info" | "success" | "warn" | "reward";
}

export interface BattleUnit {
  uid: string;
  side: "ally" | "enemy";
  slot: number;
  name: string;
  emoji: string;
  faction: FactionId;
  class: ClassId;
  stars: Rarity;
  stats: HeroStats;
  hp: number;
  maxHp: number;
  energy: number;
  skills: Skill[];
  statuses: StatusEffect[];
  portraitGradient: [string, string];
  signatureColor: string;
}

export interface BattleLog {
  at: number;
  text: string;
  actor?: string;
  target?: string;
  amount?: number;
  kind: "attack" | "skill" | "heal" | "status" | "death" | "info" | "victory" | "defeat";
}

export interface BattleResult {
  winner: "ally" | "enemy";
  turns: number;
  log: BattleLog[];
  survivors: BattleUnit[];
}
